[package]
name = "macro-string"
version = "0.1.2"
authors = ["David Tolnay <dtolnay@gmail.com>"]
categories = ["development-tools::procedural-macro-helpers"]
description = "Eager evaluation of macros like `concat!` and `env!`"
documentation = "https://docs.rs/macro-string"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dtolnay/macro-string"
rust-version = "1.61"

[dependencies]
proc-macro2 = { version = "1", default-features = false }
quote = { version = "1", default-features = false }
syn = { version = "2.0.98", default-features = false, features = ["parsing", "printing"] }

[dev-dependencies]
macro-string-eval = { path = "tests/eval", version = "0" }
rustversion = "1.0.19"
serde_json = "1"
syn = { version = "2", default-features = false, features = ["printing", "proc-macro"] }
trybuild = { version = "1.0.103", features = ["diff"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--generate-link-to-definition"]

[workspace]
members = ["tests/eval"]
